config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "recommendations", to: "recommendations#my_recommendations"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/recommendations_controller.rb
require_relative "../../lib/chat_gpt.rb"

class RecommendationsController < ApplicationController
  include OpenAIApiService

  def my_recommendations
    # Get form data from params
    query = params[:query]
    recommendation_type = params[:recommendation_type]

    # make sure they select at least one option
    if params[:options].present?
      options = params[:options]

      # Call API service
      response =
        OpenAIApiService.generate_recommendations(
          query,
          recommendation_type,
          options
        )
      # handle api exception
      if response
        @recommendations = response["choices"][0]["text"]

        # Render response in my_recommendations view
        render "recommendations/my_recommendations"
      else
        flash[:alert] = "There was an error, please try again"
        redirect_to root_path
      end
    else
      flash[:alert] = "Please select at least one matching option"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TuneUp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", :media => "all", "data-turbolinks-track" => true %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>TuneUp</title>
  </head>
  <body>
    <div class="row">
      <div class="col"></div>
      <div class="col">
        <div class="container p-5 my-5 bg-dark text-white">
          <img src="https://i.ibb.co/1Yg1ncM/tuneup.png" class="img-fluid">
          <%= form_tag recommendations_path, method: :get do %>
            <div class="mb-3">
              <%= label_tag("input-query", "Enter a song or an artist:", class: "form-label") %>
              <%= text_field_tag(
                :query,
                nil,
                class: "form-control",
                required: true,
                maxlength: 50
              ) %>
            </div>
            <div class="mb-3">
              <%= label_tag(
                "recommendation-type",
                "Select recommendation type:",
                class: "form-label"
              ) %>
              <div class="form-check">
                <%= radio_button_tag(
                  :recommendation_type,
                  "song",
                  checked = true,
                  class: "form-check-input"
                ) %>
                <%= label_tag("radio-song", "Song", class: "form-check-label") %>
              </div>
              <div class="form-check">
                <%= radio_button_tag(
                  :recommendation_type,
                  "artist",
                  checked = false,
                  class: "form-check-input"
                ) %>
                <%= label_tag("radio-artist", "Artist", class: "form-check-label") %>
              </div>
            </div>
            <div class="mb-3">
              <%= label_tag("options", "Select matching options:", class: "form-label") %>
              <div class="form-check">
                <%= check_box_tag("options[]", "mood", checked = false, class: "form-check-input") %>
                <%= label_tag("checkbox-mood", "Mood", class: "form-check-label") %>
              </div>
              <div class="form-check">
                <%= check_box_tag("options[]", "tempo", checked = false, class: "form-check-input") %>
                <%= label_tag("checkbox-tempo", "Tempo", class: "form-check-label") %>
              </div>
              <div class="form-check">
                <%= check_box_tag("options[]", "genre", checked = false, class: "form-check-input") %>
                <%= label_tag("checkbox-genre", "Genre", class: "form-check-label") %>
              </div>
              <div class="form-check">
                <%= check_box_tag("options[]", "style", checked = false, class: "form-check-input") %>
                <%= label_tag("checkbox-style", "Style", class: "form-check-label") %>
              </div>
              <div class="form-check">
                <%= check_box_tag(
                  "options[]",
                  "instrumentation",
                  checked = false,
                  class: "form-check-input"
                ) %>
                <%= label_tag(
                  "checkbox-instrumentation",
                  "Instrumentation",
                  class: "form-check-label"
                ) %>
              </div>
              <div class="form-check">
                <%= check_box_tag("options[]", "theme", checked = false, class: "form-check-input") %>
                <%= label_tag("checkbox-theme", "Theme", class: "form-check-label") %>
              </div>
            </div>
            <%= submit_tag("Get Recommendations", class: "btn btn-outline-dark") %>
          <% end %>
        </div>
      </div>
      <div class="col"></div>
    </div>

  </body>
</html>

app/views/recommendations/my_recommendations.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>TuneUp</title>
  </head>
  <body>
    <div class="row">
      <div class="col col-sm"></div>
      <div class="col-8 col-sm">
        <div class="container p-3 my-5 bg-dark text-white">
          <img src="https://i.ibb.co/1Yg1ncM/tuneup.png" class="img-fluid">
          <div class="card card-header">
            <%= simple_format @recommendations %>
            <%= link_to("Start Over", root_path, class: "btn btn-outline-dark") %>
          </div>
        </div>
      </div>
      <div class="col col-sm"></div>
    </div>

  </body>
</html>